### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by kavemun** [google-aai/tf-serving-k8s-tutorial#2]
Hi, 

I am trying to run the example on the ReadMe. After updating the yaml to my image file, and sending a request from the client, I got the following error
`
$ python resnet_client.py --server localhost --port 9000 cat_sample.jpg
Traceback (most recent call last):
  File "resnet_client.py", line 155, in <module>
    main()
  File "resnet_client.py", line 94, in main
    args.server, args.port, args.model, jpeg_batch)
  File "resnet_client.py", line 149, in predict_and_profile
    result = stub.Predict(request, 60.0)  # 60 second timeout
  File "/Users/kahmun/tf-serving-k8s-tutorial/client/client/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 310, in __call__
    self._request_serializer, self._response_deserializer)
  File "/Users/kahmun/tf-serving-k8s-tutorial/client/client/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 196, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed")`

The external-IP for the LoadBalancer is <pending>

`$ kubectl get svc
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes       ClusterIP      10.96.0.1       <none>        443/TCP          1h
resnet-service   LoadBalancer   10.101.188.76   <pending>     9000:31072/TCP   1h`

I read that when running in minikube, i should use NodePort instead, but switching to NodePort returns the same error. Is there anything that I am still doing wrong?

Also I was using the Dockerfile which was deleted in a previous commit, I don't think that is the issue could it?

**Comment by bkungfoo** [comment]
Please switch to the branch march-2018 for the tutorial. The master branch
is currently broken since we are in the process of updating it for another
tutorial. :)

**Comment by kavemun** [comment]
Hi Brian,

Thanks for the reply, but I am working on the upgrade-to-tf-1.8 branch if that is the march-2018 branch that you are referring to. It still returns me the same error. Is the new tutorial going to be updated soon?

**Comment by bkungfoo** [comment]
Hi Kah,

We will have a new tutorial out by early next week. I will be working on
the github documentation for a couple of days afterwards, so I will let you
know once the project is fully up to date.

I may have some time later next week to look into the minikube issue. May I
ask what your computer's native OS is? I've only tested this on my macbook
which might have had some local configurations that I forgot to log.

Best,
Brian

**Comment by kavemun** [comment]
Hi Brian,

I have tested both on MacOS and Ubuntu 18.04. Both have the same results.
Thanks for the help.
